### ISSUE TITLE
Where is the 0.15 version?

### ISSUE THREAD

**Issue by abourdon** [FraunhoferIOSB/FROST-Client#2]
Hi,

Documentation says there is the 0.15 version available in jcenter.bintray.com. However, I can only reach the 0.10 version (btw under the SensorThingsClient artifactId)

Is jcenter.bintray still in use?

Thanks,
Aurélien

**Comment by hylkevds** [comment]
Yes, it is.
With the rename to FROST-Server we directly cleaned up the directory structure as well, so everything is one level deeper:

The full link to the HTTP server is:
http://dl.bintray.com/fraunhoferiosb/Maven/de/fraunhofer/iosb/ilt/FROST-Server/FROST-Server.HTTP/

At some point we will clean out older versions, once they are most likely not used any more.

**Comment by hylkevds** [comment]
And for some reason jcentre did not pick up on the rename and doesn't correctly copy artifacts to jcentre. I'll send another support request about that...

**Comment by abourdon** [comment]
Ok thanks,

As a workaround we can use the dl.bintray.com as a Maven repository:

```xml
<repository>
   <id>fraunhoferisob</id>
   <url>http://dl.bintray.com/fraunhoferiosb/Maven</url>
</repository>
```

Then use the 0.15 version as normally:

```xml
<dependency>
   <groupId>de.fraunhofer.iosb.ilt</groupId>
   <artifactId>FROST-Client</artifactId>
   <version>0.15</version>
</dependency>
```

Regards,
Aurélien

**Comment by hylkevds** [comment]
The jcenter version is up-to-date again.
