### ISSUE TITLE
Problems building with Java 1.8 due to slf4j-api and mockito-core

### ISSUE THREAD

**Issue by robinzclark777** [FraunhoferIOSB/FROST-Client#200]
@hylkevds , I was trying to build this application this morning and received errors about the slf4j and mockito core libraries being compiled with an incompatible version of Java.  This is the original error that I received:

[ERROR] /D:/frostclient/FROST-Client/src/test/java/de/iosb/fraunhofer/ilt/sta/MqttTest.java:[60,26] cannot access org.mockito.Mockito
[ERROR]   bad class file: C:\Users\rclark\.m2\repository\org\mockito\mockito-core\5.1.1\mockito-core-5.1.1.jar(org/mockito/Mockito.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

I was able to build successfully after I changed the sl4j-api.version to 1.7.36 and the mockito.version to 4.0.0.  I just randomly chose an earlier version of the libraries. Let me know how I can help to resolve this issue.  Are you hoping to change the application to use a more up to date version of Java?  Or would you like for me to do a pull request to update the versions of these two libraries so that they will be compatible with Java 1.8?

**Comment by hylkevds** [comment]
Version 55.0 is Java 11, you need at least this version, since the two libraries you mentioned don't support Java 8 (1.8) any more.

I would strongly recommend upgrading to at least Java 11, since Java 8 support has ended quite a while ago. And even 11 will run out of standard support this year.

Is there a specific reason you are still on Java 8?

**Comment by robinzclark777** [comment]
The pom.xml file in the root of the project is still specifying Java 1.8.  Should it be changed to point to 11?

**Comment by hylkevds** [comment]
Ah, good point, we've forgotten to update that.

**Comment by hylkevds** [comment]
Should be fixed now.

**Comment by robinzclark777** [comment]
You're the best! I was worried there was something I didn't understand.
Glad to know. I'm hoping that I can begin to contribute in some way to your
project.

I'll start with small things because I'm new to this.  But surely I have
some skills that can be useful.
