### ISSUE TITLE
Need more information for DataArray for Observation creation

### ISSUE THREAD

**Issue by bblocher777** [FraunhoferIOSB/FROST-Client#204]
Thus far I have used the http://localhost:8080/FROST-Server/v1.0 URL (with the frost-server running) for the examples provided in the readme file without issue.  I am having issues using that URL for the Data Array for Observation creation example as it appends /createObservations to the URL provided which gives me back a status 500 error.  Please advise

**Comment by hylkevds** [comment]
5xx errors are server errors. There should be a message in the log file about it. Please have a look there.

**Comment by bblocher777** [comment]
Turns out it didn't like the Datastream datastream1 object.  Using the EntityList<Datastream> dataStreams instead was successful.
