### ISSUE TITLE
NullPointerException in checkAutoRefreshTimer method when using TokenManagerOpenIDConnect

### ISSUE THREAD

**Issue by tessaRuckstuhl** [FraunhoferIOSB/FROST-Client#288]
I am encountering a **NullPointerException** in the `checkAutoRefreshTimer` method of the `TokenManagerOpenIDConnect` class when setting up OpenID Connect. The exception occurs at the line `refreshTask.cancel()`. Here is the code reference: 
https://github.com/FraunhoferIOSB/FROST-Client/blob/693da44b9dd87ad8c0a4befbe588207edde09d25/src/main/java/de/fraunhofer/iosb/ilt/sta/service/TokenManagerOpenIDConnect.java#L204
The issue arises when setting `autoRefresh` to true. 
Setting `autoRefresh` to false works, but the token eventually expires, requiring autoRefresh to be enabled for proper functionality.
It seems that there is a missing check to ensure refreshTask is not null before calling cancel on it, leading to the **NullPointerException**.

Has anyone else successfully implemented this feature?
Is there a recommended approach to ensure refreshTask is properly initialized before calling cancel?

Any guidance or suggestions to resolve this issue would be greatly appreciated.

Thank you!

**Comment by hylkevds** [comment]
Can you try version 0.45-SNAPSHOT to see if my fix works?
You may have to temporarily add the oss snapshot repository to your pom:
```
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
```

**Comment by tessaRuckstuhl** [comment]
Thank you for your fast reply. I tried your solution and it solves the **NullPointerException**. However, now in the method https://github.com/FraunhoferIOSB/FROST-Client/blob/693da44b9dd87ad8c0a4befbe588207edde09d25/src/main/java/de/fraunhofer/iosb/ilt/sta/service/TokenManagerOpenIDConnect.java#L107

The `client_id` is not set on the token request (only the grant_type and refresh_token parametes are set), causing a 400 response with json:
```
 {
	"error": "invalid_client",
	"error_description": "Invalid client credentials"
}
```

I believe what is missing here now, is adding the client_id to the parameters. 
Like so:         
 `   parameters.add(new BasicNameValuePair("client_id", clientId));`

**Comment by tessaRuckstuhl** [comment]
It works now, the second fix fixed it for me! Thank you 👍 
Will you add the fix to official release?

**Comment by hylkevds** [comment]
Yes, I'll create a new release soon.
