### ISSUE TITLE
ExpandedEntity behaving unexpected

### ISSUE THREAD

**Issue by SirYwell** [FraunhoferIOSB/FROST-Client#37]
I wanted to use an Expansion to fetch a Datastream with its inner entities and inner entities of those entities.
```java
Expansion.of(EntityType.DATASTREAM)
                    .with(ExpandedEntity.from(EntityType.THING, EntityType.LOCATIONS))
```
This is my code I expected to work but it throws an InvalidRelationException. I checked the implementation and found out that it will check `EntityType.LOCATIONS.hasRelationTo(EntityType.THING)` (but a list of Locations doesn't have a relation to one Thing) instead of `EntityType.THING.hasRelationTo(EntityType.LOCATIONS)`. The `ExpandedEntity#toString` method _would_ produce the expected output that can be used for $expand, so I guess I'm using it right.

I can create a pull request changing the direction of the relation check if you agree that this is a bug and my usage is correct.

**Comment by hylkevds** [comment]
It does indeed seem that your usage is how it is intended. The example in the JavaDoc also indicates this:
```
 * Expansion.of(EntityType.THING)
 * 			.with(ExpandedEntity.of(EntityType.LOCATIONS))
 * 			.and(ExpandedEntity.of(EntityType.DATASTREAMS, EntityType.OBSERVATIONS))
 * 			.and(ExpandedEntity.of(EntityType.DATASTREAMS, EntityType.SENSOR));

```
A patch would be welcome!

This expand-builder needs work, since it does not produce very nice expands, and does not allow one to set query parameters for those expands. While 
`Things?$expand=Datastreams/Observations,Datastreams/Sensor`
is correct according to the standard, it is better to use 
`Things?$expand=Datastreams($expand=Observations,Sensor)`
since that allows one to add $select, $orderby and $top to all items in the expand: 
```
Things?
  $expand=Datastreams(
    $select=id,name;
    $expand=
      Observations(
        $top=1;
        $orderby=phenomenonTime desc;
        $select=phenomenonTime,result
      ),
      Sensor(
        $select=id,name
      )
  )
```
But the system does not allow one to do this at the moment...

**Comment by SirYwell** [comment]
So basically, an Expansion could accept something similar to a `Query` from my understandings:
```java
Expansion.of(EntityType.THING)
            .with(EntityType.DATASTREAMS,
                new Query(...).select("id", "name")
                    .expand(Expansion.of(EntityType.DATASTREAMS)
                        .with(EntityType.OBSERVATIONS, new Query(...)
                            .top(1)
                            .orderBy("phenomenomTime desc")
                            .select("phenomenomTime", "result"))
                        .and(EntityType.SENSOR,
                            new Query(...).select("id", "name")
                        )
                    )
            );
```
As this is just a raw design proposal, there are a few points to think about:
- Query should probably split up into a SensorThingsService-agnostic builder and an actual Query
- I didn't use ExpandedEntity here. The methods could be overloaded accepting an EntityType and a Query(Builder), it could be handled internally to bring EntityType and the query together to reduce verbosity of the builder (ExpandedEntity could be used to, like `ExpandedEntity.from(EntityType, Query)` but that makes it harder to read in my opinion).

ExpandedEntity could still be used for simple Expansions but I would only fix the relation check for now. That way, using ExpandedEntity would produce something like
`Things?$expand=Datastreams/Observations,Datastreams/Sensor`
while using my suggestion could produce the more powerful expansion model.

**Comment by hylkevds** [comment]
Yes, that looks like the right way to do it.
Thank you for looking into it!
