### ISSUE TITLE
Using Gradle as Build Tool

### ISSUE THREAD

**Issue by rschlund** [FraunhoferIOSB/FROST-Client#6]
Just had to figure out, how to use gradle as build tool. Perhaps you can integrate this information:
In app  build.gradle you have to add:
    implementation "de.fraunhofer.iosb.ilt:FROST-Client:0.15" 
in the dependencies section
and in project build.gradle you have to add         
    maven { url "https://dl.bintray.com/fraunhoferiosb/Maven" } 
in the repositories section

**Comment by hylkevds** [comment]
Thanks, I'll add a "use in gradle" section to the Readme.
