### ISSUE TITLE
Not all server interaction throws exception in case of communication problems

### ISSUE THREAD

**Issue by GDue** [FraunhoferIOSB/FROST-Client#8]
I have a server set up to work with BasicAuthentification.

Then I execute the following line:
ObservedProperty obsProp=service.observedProperties().find(obsPropId);

With the proper (wrong) configuration this yields in a 401 response code.
There is no exception thrown (as expected and as described in the java doc). Instead a null is returned.

**Comment by hylkevds** [comment]
Indeed, that client just eats up all the status codes. That's not nice.
I'll update it so it throws an extended ServiceFailureException that also makes the exact status code available. That way you can catch the ServiceFailureException if you're not interested in the exact error, or separately catch the extended version and see the exact status code.

**Comment by GDue** [comment]
Hi Hylke,

a fix would fix that small flaw. But that bug is not severe and by far not a show stopper for us.
Right now we have been porting the client for android (works but somehow ugly) so maybe we have a few more things until we are ready.
So you might want to wait a bit with a new version.
BR
Gerhard

**Comment by hylkevds** [comment]
I've pushed the update to master, so you can try them out.
