### ISSUE TITLE
Additional header before every HttpRequest

### ISSUE THREAD

**Issue by smilehappy126** [FraunhoferIOSB/FROST-Client#80]
Hi,
    I've been attempting to add or manipulate http request header for authentication usage before the "SensorThingsService" send this request to server. I've tried TokenManager but in vain. My goal is to ask user to provide token and send this token with FROST-Client's each http requests. Is there a documentation to guide or any existed case to follow?
   Any advice would be helpful.

**Comment by hylkevds** [comment]
The TokenManager is the way to do this.
If you register a TokenManager on the SensorThingsService, the `addAuthHeader` of the TokenManager is called before each request.
The TokenManagerJWT implementation is an example of how this is supposed to work.
Another example is in the [AuthHeader.java](https://github.com/FraunhoferIOSB/FROST-Manager/blob/bbb1136a1c14d8d1fe2ed0494125b9bf8a566c32/src/main/java/de/fraunhofer/iosb/ilt/sensorthingsmanager/auth/AuthHeader.java#L47) class of the FROST-Manager application.

**Comment by smilehappy126** [comment]
Thanks!! Follow TokenManageJWT is really helpful.
